# Generated by Django 4.1 on 2022-08-16 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorName', models.CharField(max_length=50, verbose_name='Author Name')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('BookName', models.CharField(max_length=50, verbose_name='Book Name')),
                ('BookId', models.IntegerField(primary_key=True, serialize=False, verbose_name='Book Id')),
                ('BookPrice', models.CharField(max_length=50, verbose_name='Book Price')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.author')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Customer Id')),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.books')),
            ],
        ),
    ]
