# Generated by Django 4.0.6 on 2022-08-31 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_Name', models.CharField(max_length=122)),
                ('room_book_date', models.DateField()),
                ('meeting_start_time', models.TimeField()),
                ('room_leave_date', models.TimeField()),
                ('meeting_end_time', models.TimeField()),
                ('room_booked_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
