# Generated by Django 4.0.6 on 2022-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_leave_date',
            field=models.DateField(),
        ),
    ]
