# Generated by Django 4.0.6 on 2022-09-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_room_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_leave_date',
        ),
    ]
