# Generated by Django 4.0.6 on 2022-09-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_room_room_leave_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
