# Generated by Django 4.0.6 on 2022-09-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='grant_meeting',
            field=models.BooleanField(default=False),
        ),
    ]
