# Generated by Django 4.0.6 on 2022-08-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=50, verbose_name='Author Name')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('BookName', models.CharField(max_length=50, verbose_name='Book Name')),
                ('BookId', models.IntegerField(primary_key=True, serialize=False, verbose_name='Book Id')),
                ('BookPrice', models.IntegerField(verbose_name='BookPrice')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStoreWebsite.author')),
            ],
        ),
    ]
