# Generated by Django 4.0.6 on 2022-08-30 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BookStoreWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='User',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='Author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BookStoreWebsite.author'),
        ),
        migrations.AlterField(
            model_name='books',
            name='BookId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Book Id'),
        ),
        migrations.AlterField(
            model_name='books',
            name='BookName',
            field=models.CharField(blank=True, max_length=50, verbose_name='Book Name'),
        ),
        migrations.AlterField(
            model_name='books',
            name='BookPrice',
            field=models.IntegerField(blank=True, verbose_name='BookPrice'),
        ),
    ]
